- name: check all hosts accessbility
  hosts: "{{env}}"
  become: true
  gather_facts: false
  tasks:
    - import_tasks: roles/common/tasks/precheck_host_connection.yml
      tags: always

#-------------Copy iFix patch to this folder and Patch path----------
- hosts: IBM_HTTP_Server_{{env}}
  gather_facts: false
  remote_user: "{{servers_user}}"
  vars_files:
    - ./vars/{{ env }}.yml
  pre_tasks:
    - import_tasks: roles/common/tasks/set_common_facts.yml
      tags: ['ifix-deployment']
  tasks:
    - include_tasks: tasks/common_ifix_steps.yml
      tags: ['common-ifix-steps']

#-----------------Stop and verify all servers------------------------
#-----------------Pause all LQE/LDX reindexing--------------------------

#----------------Taking the backup of Workarea folder and Apply iFix-------
- hosts: LQE_{{env}}  #"{{apply_iFix_servers}}"
  gather_facts: false
  remote_user: "{{servers_user}}"
  vars_files:
    - ./vars/{{ env }}.yml
  pre_tasks:
    - import_tasks: roles/common/tasks/set_common_facts.yml
      tags: ['ifix-deployment']
  tasks:
    - include_tasks: tasks/ifix_steps.yml
      tags: ['backup-apply-ifix']     

#-----------Rename war files---------------------------
- hosts: LQE_{{env}}  #"{{rename_wars}}"
  gather_facts: false
  remote_user: "{{servers_user}}"
  vars_files:
    - ./vars/{{ env }}.yml
  pre_tasks:
    - import_tasks: roles/common/tasks/set_common_facts.yml
      tags: ['ifix-deployment']
  tasks:    
    - include_tasks: tasks/rename_all_wars.yml
      vars:
         source_path: "{{input_data[item]['source_path']}}"
         destination_path: "{{input_data[item]['destination_path']}}"
      loop: "{{ input_data.keys() | list }}"       
      tags: ['rename-wars']

#--------------------Copy LDX, LQE, RS war files---------------------------- 
- hosts: LQE_{{env}} 
  gather_facts: false
  remote_user: "{{servers_user}}"
  vars_files:
    - ./vars/{{ env }}.yml
  pre_tasks:
    - import_tasks: roles/common/tasks/set_common_facts.yml
      tags: ['ifix-deployment']
  tasks:
    - name: Remove old file
      vars: 
        remove_path: "{{backup_workarea_path}}/apps/lqe.war.org"  
      import_role:
         name: remove_operation 
      tags: ['copy-wars'] 

    - name: move files
      vars:
        move_source_path: "{{backup_workarea_path}}/apps/lqe.war"
        move_destination_path: "{{backup_workarea_path}}/apps/lqe.war.org"
      import_role:
         name: move_operation 
      tags: ['copy-wars']  
    
    - name: Check file is exist or not
      vars:
        file_path: "{{backup_workarea_path}}/apps/lqe.war.org"
      import_role:
         name: stat_operation 
      tags: ['copy-wars'] 

    - name: Copy LQE war files
      vars:
       source_path: "{{install_binary_path}}/{{PATCH_NAME_TO_DEPLOY}}/lqe.war.zip"
       destination_path: "{{backup_workarea_path}}/apps/"
      import_role:
        name: copy_operation
      tags: ['copy-wars']

    - name: Unarchive LQE
      vars: 
        unzip_source: "{{backup_workarea_path}}/apps/lqe.war.zip"
        unzip_destination: "{{backup_workarea_path}}/apps/lqe.war"
      import_role:
        name: unzip_wars
      tags: ['copy-wars']   
   

#--- Copy LDX war files------------------
- hosts: LDX_{{env}}
  gather_facts: false
  remote_user: "{{servers_user}}"
  vars_files:
    - ./vars/{{ env }}.yml
  pre_tasks:
    - import_tasks: roles/common/tasks/set_common_facts.yml
      tags: ['copy-wars']
  tasks:
     - name: Remove old file
       vars: 
         remove_path: "{{backup_workarea_path}}/apps/ldx.war.org"  
       import_role:
         name: remove_operation 
       tags: ['copy-wars'] 
       
     - name: Move LDX war files
       vars:
        move_source_path: "{{backup_workarea_path}}/apps/ldx.war"
        move_destination_path: "{{backup_workarea_path}}/apps/ldx.war.org"
       import_role:
        name: move_operation
       tags: ['copy-wars']

     - name: Check file is exist or not
       vars:
         file_path: "{{backup_workarea_path}}/apps/ldx.war.org"
       import_role:
         name: stat_operation 
       tags: ['copy-wars'] 

     - name: Copy LDX war files
       vars:
         source_path: "{{install_binary_path}}/{{PATCH_NAME_TO_DEPLOY}}/ldx.war.zip"
         destination_path: "{{backup_workarea_path}}/apps/"
       import_role:
         name: copy_operation
       tags: ['copy-wars']

     - name: Unarchive LDX
       vars: 
         unzip_source: "{{backup_workarea_path}}/apps/ldx.war.zip"
         unzip_destination: "{{backup_workarea_path}}/apps/ldx.war"
       import_role:
         name: unzip_wars
       tags: ['copy-wars']

#----------------Copr RS war files------------------
- hosts: JRS_{{env}} 
  gather_facts: false
  remote_user: "{{servers_user}}"
  vars_files:
    - ./vars/{{ env }}.yml
  pre_tasks:
    - import_tasks: roles/common/tasks/set_common_facts.yml
      tags: ['copy-wars']
  tasks:
    - name: Remove old file
      vars: 
         remove_path: "{{backup_workarea_path}}/apps/rs.war.org"  
      import_role:
         name: remove_operation 
      tags: ['copy-wars'] 
       
    - name: Move JRS war files
      vars:
       move_source_path: "{{backup_workarea_path}}/apps/rs.war"
       move_destination_path: "{{backup_workarea_path}}/apps/rs.war.org"
      import_role:
        name: move_operation
      tags: ['copy-wars']

    - name: Copy JRS war files
      vars:
       source_path: "{{install_binary_path}}/{{PATCH_NAME_TO_DEPLOY}}/rs.war.zip"
       destination_path: "{{backup_workarea_path}}/apps/"
      import_role:
        name: copy_operation
      tags: ['copy-wars']

    - name: Unarchive JRS
      vars: 
        unzip_source: "{{backup_workarea_path}}/apps/rs.war.zip"
        unzip_destination: "{{backup_workarea_path}}/apps/rs.war"
      import_role:
        name: unzip_wars
      tags: ['copy-wars']

#-------------------repotool clean command--------------
#------------------Start and verify all servers started---------------
#-----------------Verify all applications are accessible from UI---------------
#-----------------Resume all LQE/LDX reindexing---------------------------

